#!/usr/bin/with-contenv bash

set -euo pipefail

# Pass gpu flags if mounted.
if ls /dev/dri/renderD* 1> /dev/null 2>&1 && [[ -z ${DISABLE_DRI+x} ]] && ! command -v nvidia-smi >/dev/null 2>&1; then
  HW3D="-hw3d"
else
  HW3D=""
fi

if [[ -z ${DRINODE+x} ]]; then
  DRINODE="/dev/dri/renderD128"
fi

WIDTH="${CUSTOM_RES_W:-1366}"
HEIGHT="${CUSTOM_RES_H:-768}"

exec s6-setuidgid abc \
  /usr/local/bin/Xvnc "$DISPLAY" \
    ${HW3D} \
    -PublicIP 127.0.0.1 \
    -drinode "${DRINODE}" \
    -disableBasicAuth \
    -SecurityTypes None \
    -AlwaysShared \
    -http-header Cross-Origin-Embedder-Policy=require-corp \
    -http-header Cross-Origin-Opener-Policy=same-origin \
    -geometry "${WIDTH}x${HEIGHT}" \
    -sslOnly 0 \
    -RectThreads 2 \
    -websocketPort 6901 \
    -interface 0.0.0.0 \
    -Log *:stdout:10